# Vagrantfile for setting up a 3-node K3s Kubernetes cluster (1 master, 2 workers)
Vagrant.configure("2") do |config|
    # Define a common base configuration for all VMs
    config.vm.box = "ubuntu/focal64"  # Ubuntu 20.04
  
    # Define the master node
    config.vm.define "k3s-master-2" do |master|
      master.vm.hostname = "k3s-master-2"
      master.vm.network "private_network", ip: "192.168.56.20"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      master.vm.provision "shell", path: "k3s-master.sh"
    end
  
    # Define the worker node
    config.vm.define "k3s-worker2-2" do |worker2|
      worker2.vm.hostname = "k3s-worker2-2"
      worker2.vm.network "private_network", ip: "192.168.56.12"
      worker2.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      worker2.vm.provision "shell", path: "k3s-worker.sh", args: ["192.168.56.20"]
    end
  end
