Vagrant.configure("2") do |config|
  nodes = [
    { name: "master", ip: "192.168.57.10" },
    { name: "worker1", ip: "192.168.57.11" },
    { name: "worker2", ip: "192.168.57.12" }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |machine|
      machine.vm.box = "ubuntu/jammy64"
      machine.vm.hostname = node[:name]
      machine.vm.network "private_network", ip: node[:ip]
      machine.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      machine.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y curl apt-transport-https
      SHELL
    end
  end
end

